name: the_movies_flutter_app
description: "An app that lists all upcoming movies"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_riverpod: ^3.2.0
  flutter_svg: ^2.2.3
  dio: ^5.9.1
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_hd.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:

    - family: Poppins-Black.ttf
      fonts:
        - asset: 'assets/fonts/Poppins-Black.ttf'

